#!/bin/bash

if [ $# -lt 2 ]
  then
    echo "Usage: $0 <language> <filename> [args]"
    echo "  Where <language> can be one of the following: go, node, python, rust, fs, swift, java, c, sh"
    exit
fi

case "$1" in
    
    "go")
        docker run --rm -v "$PWD":/mycode -w /mycode golang:1.9-alpine go run "${@:2}"
        ;;
    
    "node")
        docker run --rm -v "$PWD":/mycode -w /mycode node:8-alpine node "${@:2}"
        ;;

    "python")
        docker run --rm -v "$PWD":/mycode -w /mycode python:3-alpine python "${@:2}"
        ;;

    "rust")
        docker run --rm -v "$PWD"/"$2":/mycode/"$2" -w /mycode frolvlad/alpine-rust /bin/sh -c " \
        rustc -o rust-bin $2; \
        ./rust-bin \"${@:3}\""
        ;;

    "swift")
        docker run --rm -v "$PWD"/"$2":/mycode/"$2" -w /mycode swift:4 swift "${@:2}"
        ;;

    "fs")
        ARGS="\"$3\" ${@:4}"
        docker run --rm -v "$PWD"/"$2":/mycode/"$2" -w /mycode fsharp:4.1 /bin/sh -c " \
        fsharpc -o mycode.exe $2 > /dev/null; \
        mono mycode.exe ${ARGS}"
        ;;

    "c")
        ARGS="\"$3\" ${@:4}"
        docker run --rm -v "$PWD"/"$2":/mycode/"$2" -w /mycode frolvlad/alpine-gcc /bin/sh -c " \
        gcc -o mycode $2 > /dev/null; \
        ./mycode ${ARGS}"
        ;;

    "sh")
        docker run --rm -v "$PWD":/mycode -w /mycode alpine:3.7 /bin/sh "${@:2}"
        ;;

    "java")
        FILE=$(basename $2)
        docker run --rm -v "$PWD"/"$2":/mycode/"$2" -w /mycode anapsix/alpine-java:8_jdk /bin/sh -c " \
        javac $2; \
        java -cp \"$(dirname $2)\" \"${FILE%$'.java'}\" ${@:3}"
        ;;

    *)
        echo "Unknown language $1"
        ;;
esac
